site_name: OpenVoiceChat Docs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Usage:
    - Commands: usage/commands.md
    - Permissions: usage/permissions.md
  - API Reference: classes.md
  - Support:
    - Discord: support/discord.md
    - GitHub: support/github.md
  - License: license.md
theme:
    name: 'material'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [openvoicechat]
        options:
          docstring_style: sphinx
          docstring_section_style: table
          heading_level: 2
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_docstring_description: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_source: true
          summary: true